stages:
  - check
  - test

include:
  - project: "GNOME/citemplates"
    file: "templates/default-rules.yml"
  - project: "GNOME/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"

variables:
  BUNDLE: "MQTTy-nightly.flatpak"
  MANIFEST_PATH: "build-aux/io.github.otaxhu.MQTTy.Devel.json"
  FLATPAK_MODULE: "MQTTy"
  APP_ID: "io.github.otaxhu.MQTTy.Devel"
  RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"

flatpak:
  image: 'quay.io/gnome_infrastructure/gnome-runtime-images:gnome-47'
  extends: ".flatpak@x86_64"

# Configure and run rustfmt
# Exits and builds fails if on bad format
rustfmt:
  image: "rust:slim"
  script:
    - rustup component add rustfmt
    # Create blank versions of our configured files
    # so rustfmt does not yell about non-existent files or completely empty files
    - echo -e "" >> src/config.rs
    - rustc -Vv && cargo -Vv
    - cargo fmt --version
    - cargo fmt --all -- --color=always --check
