[package]
name = "MQTTy"
authors = ["Oscar Pernia <oscarperniamoreno@gmail.com>"]
edition = "2021"

[profile.release]
lto = true

[dependencies]
adw = { version = "0.7.1", package = "libadwaita" }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.9", package = "gtk4", features = ["v4_8"] }
tracing = "0.1.37"
tracing-subscriber = "0.3"
