[package]
name = "MQTTy"
authors = ["Oscar Pernia <oscarperniamoreno@gmail.com>"]
edition = "2021"
version = "0.1.4"

[profile.release]
lto = true

[dependencies]
adw = { version = ">=0.8.0", package = "libadwaita", features = ["v1_8"]}
async-channel = "2.3.1"
backoff = { version = "0.4.0", features = ["async-std"] }
base64 = "0.22.1"
chrono = "0.4.41"
directories = "6.0.0"
formatx = "0.2.3"
futures = "0.3.31"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gettext-sys = { version = "0.22.5", features = ["gettext-system"] }
gtk = { version = ">=0.10", package = "gtk4", features = ["gnome_49"] }
icu = "2.0.0"
indoc = "2.0.6"
nanoid = "0.4.0"
paho = { version = "0.13.2", package = "paho-mqtt" }
rusqlite = { version = "0.37.0", features = ["bundled"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sourceview = { version = ">=0.10.0", package = "sourceview5" }
thiserror = "2.0.12"

[build-dependencies]
winresource = "0.1.20"
